import { html } from 'hono/html'
import type { Context } from 'hono'
import type { Env } from './types'
import { canAccessStaff } from './security'
export function shell(c: Context<Env>, title: string, body: any, active = '') {
  const clinic = c.get('clinic'), staff = c.get('staff')
  const nav = [['/admin','대시보드','dash'],['/admin/reservations','예약 응대','reservations'],['/admin/notifications','예약 알림','notifications'],['/admin/cases','치료 전후','cases'],['/admin/columns','원장 칼럼','columns'],['/admin/notices','공지사항','notices'],['/admin/press','언론보도','press'],['/admin/members','회원','members'],['/admin/fees','비급여 수가','fees'],['/admin/settings','진료시간·기본정보','settings'],['/admin/stats','통합 통계','stats'],['/admin/staff','직원·권한','staff'],['/admin/privacy','보유기간·파기','privacy']].filter(([path]) => canAccessStaff(staff, path))
  return c.html(html`<!DOCTYPE html><html lang="ko"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex, nofollow"><title>${title} · 관리자 · ${clinic.shortName}</title><link rel="stylesheet" href="/static/fonts/wanted-subsets.css?v=2"><link rel="stylesheet" href="/static/style.css?v=9"><link rel="stylesheet" href="/static/admin-workflow.css?v=3"><link rel="icon" href="/favicon.png"><link rel="apple-touch-icon" href="/apple-touch-icon.png"><link rel="manifest" href="/admin/manifest.webmanifest"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-title" content="도담 관리자"><meta name="apple-mobile-web-app-status-bar-style" content="default"><meta name="theme-color" content="#006AB5"></head>
  <body class="admin"><div class="admin-wrap"><aside class="admin-side"><a href="/admin" class="admin-logo">도담 · 운영실</a><p class="staff-session">${staff ? html`${staff.name} · ${{owner:'관리책임자',reception:'예약 담당',editor:'콘텐츠 담당'}[staff.role || 'owner']}` : '통계 열람 링크 (읽기 전용)'}</p><nav aria-label="운영 메뉴"><ul>${nav.map(([h,n,k]) => html`<li><a href="${h}" class="${active === k ? 'active' : ''}" ${active === k ? 'aria-current=page' : ''}>${n}</a></li>`)}</ul></nav><div class="admin-side-foot"><a href="/" target="_blank" rel="noopener noreferrer">사이트 보기 ↗</a>${staff ? html`<form method="post" action="/admin/logout"><button type="submit" class="btn btn-outline btn-sm">로그아웃</button></form>` : ''}</div></aside><main class="admin-main"><p class="workspace-label">DODAM / CLINIC OPERATIONS</p><h1 class="h2">${title}</h1>${body}</main></div><script src="/static/admin-sanitizer.js?v=1" defer></script><script src="/static/admin.js?v=6" defer></script></body></html>`)
}
