// Generated by scripts/build-image-manifest.mjs; pixel dimensions from actual assets.
export const imageManifest: Record<string, { width: number; height: number; srcset: string }> = {
  "/static/img/anesthetic-warmer-iject-on-v2.webp": {
    "width": 1400,
    "height": 1100,
    "srcset": "/static/img/anesthetic-warmer-iject-on-v2-sm.webp 640w, /static/img/anesthetic-warmer-iject-on-v2.webp 1400w"
  },
  "/static/img/denops-i-portable-intraosseous-anesthesia-v2.webp": {
    "width": 1400,
    "height": 1100,
    "srcset": "/static/img/denops-i-portable-intraosseous-anesthesia-v2-sm.webp 640w, /static/img/denops-i-portable-intraosseous-anesthesia-v2.webp 1400w"
  },
  "/static/img/dental-whitening-light-v2.webp": {
    "width": 1400,
    "height": 1100,
    "srcset": "/static/img/dental-whitening-light-v2-sm.webp 640w, /static/img/dental-whitening-light-v2.webp 1400w"
  },
  "/static/img/dr-han-hwirim-avatar-v2.webp": {
    "width": 480,
    "height": 480,
    "srcset": "/static/img/dr-han-hwirim-avatar-v2.webp 480w"
  },
  "/static/img/dr-han-hwirim-portrait-v2.webp": {
    "width": 1200,
    "height": 1500,
    "srcset": "/static/img/dr-han-hwirim-portrait-v2-sm.webp 640w, /static/img/dr-han-hwirim-portrait-v2.webp 1200w"
  },
  "/static/img/dr-han-hwirim-standing-v2.webp": {
    "width": 1200,
    "height": 1500,
    "srcset": "/static/img/dr-han-hwirim-standing-v2-sm.webp 640w, /static/img/dr-han-hwirim-standing-v2.webp 1200w"
  },
  "/static/img/iject-on-warmer-unit-v2.webp": {
    "width": 1400,
    "height": 1100,
    "srcset": "/static/img/iject-on-warmer-unit-v2-sm.webp 640w, /static/img/iject-on-warmer-unit-v2.webp 1400w"
  },
  "/static/img/iject-painless-anesthesia-gun-v2.webp": {
    "width": 1400,
    "height": 1100,
    "srcset": "/static/img/iject-painless-anesthesia-gun-v2-sm.webp 640w, /static/img/iject-painless-anesthesia-gun-v2.webp 1400w"
  },
  "/static/img/one-fil-putty-mta-v2.webp": {
    "width": 1400,
    "height": 1100,
    "srcset": "/static/img/one-fil-putty-mta-v2-sm.webp 640w, /static/img/one-fil-putty-mta-v2.webp 1400w"
  },
  "/static/img/person-vacuum-autoclave-48l-v2.webp": {
    "width": 1400,
    "height": 1100,
    "srcset": "/static/img/person-vacuum-autoclave-48l-v2-sm.webp 640w, /static/img/person-vacuum-autoclave-48l-v2.webp 1400w"
  },
  "/static/img/portable-xray-v2.webp": {
    "width": 1400,
    "height": 1100,
    "srcset": "/static/img/portable-xray-v2-sm.webp 640w, /static/img/portable-xray-v2.webp 1400w"
  },
  "/static/img/qraycam-pro-fluorescence-caries-detector-v2.webp": {
    "width": 1400,
    "height": 1100,
    "srcset": "/static/img/qraycam-pro-fluorescence-caries-detector-v2-sm.webp 640w, /static/img/qraycam-pro-fluorescence-caries-detector-v2.webp 1400w"
  },
  "/static/img/suwon-dodam-dental-building-front-v2.webp": {
    "width": 1024,
    "height": 768,
    "srcset": "/static/img/suwon-dodam-dental-building-front-v2-sm.webp 640w, /static/img/suwon-dodam-dental-building-front-v2.webp 1024w"
  },
  "/static/img/suwon-dodam-dental-chair-unit-v2.webp": {
    "width": 1400,
    "height": 1100,
    "srcset": "/static/img/suwon-dodam-dental-chair-unit-v2-sm.webp 640w, /static/img/suwon-dodam-dental-chair-unit-v2.webp 1400w"
  },
  "/static/img/suwon-dodam-dental-child-room-v2.webp": {
    "width": 1400,
    "height": 1100,
    "srcset": "/static/img/suwon-dodam-dental-child-room-v2-sm.webp 640w, /static/img/suwon-dodam-dental-child-room-v2.webp 1400w"
  },
  "/static/img/suwon-dodam-dental-consult-room-v2.webp": {
    "width": 1600,
    "height": 1100,
    "srcset": "/static/img/suwon-dodam-dental-consult-room-v2-sm.webp 640w, /static/img/suwon-dodam-dental-consult-room-v2.webp 1600w"
  },
  "/static/img/suwon-dodam-dental-information-desk-v2.webp": {
    "width": 1600,
    "height": 1100,
    "srcset": "/static/img/suwon-dodam-dental-information-desk-v2-sm.webp 640w, /static/img/suwon-dodam-dental-information-desk-v2.webp 1600w"
  },
  "/static/img/suwon-dodam-dental-reception-desk-v2.webp": {
    "width": 1600,
    "height": 1100,
    "srcset": "/static/img/suwon-dodam-dental-reception-desk-v2-sm.webp 640w, /static/img/suwon-dodam-dental-reception-desk-v2.webp 1600w"
  },
  "/static/img/suwon-dodam-dental-sterilization-room-v2.webp": {
    "width": 1600,
    "height": 1100,
    "srcset": "/static/img/suwon-dodam-dental-sterilization-room-v2-sm.webp 640w, /static/img/suwon-dodam-dental-sterilization-room-v2.webp 1600w"
  },
  "/static/img/suwon-dodam-dental-treatment-explanation-v2.webp": {
    "width": 1024,
    "height": 683,
    "srcset": "/static/img/suwon-dodam-dental-treatment-explanation-v2-sm.webp 640w, /static/img/suwon-dodam-dental-treatment-explanation-v2.webp 1024w"
  },
  "/static/img/suwon-dodam-dental-treatment-room-v2.webp": {
    "width": 1600,
    "height": 1100,
    "srcset": "/static/img/suwon-dodam-dental-treatment-room-v2-sm.webp 640w, /static/img/suwon-dodam-dental-treatment-room-v2.webp 1600w"
  },
  "/static/img/suwon-dodam-dental-waiting-lounge-v2.webp": {
    "width": 1600,
    "height": 1100,
    "srcset": "/static/img/suwon-dodam-dental-waiting-lounge-v2-sm.webp 640w, /static/img/suwon-dodam-dental-waiting-lounge-v2.webp 1600w"
  },
  "/static/img/tmj-phl-laser-v2.webp": {
    "width": 1400,
    "height": 1100,
    "srcset": "/static/img/tmj-phl-laser-v2-sm.webp 640w, /static/img/tmj-phl-laser-v2.webp 1400w"
  },
  "/static/img/vatech-green16-low-dose-ct-v2.webp": {
    "width": 1400,
    "height": 1100,
    "srcset": "/static/img/vatech-green16-low-dose-ct-v2-sm.webp 640w, /static/img/vatech-green16-low-dose-ct-v2.webp 1400w"
  }
}
